version: '3.9'

services:
  keycloak:
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER} 
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    command: 
      - start-dev 
    image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_VERSION}
    ports:
      - ${KEYCLOAK_PORT}:8080


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_IMAGE_VERSION}
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ES_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1

  search-service:
      image: search-service:latest
      container_name: search-service
      environment:
        - elastic_search_host=${elastic_search_host}
        - elastic_search_port=${elastic_search_port}
        - elastic_search_username=${elastic_search_username}
        - elastic_search_password=${elastic_search_password}
        - elastic_search_scheme=${elastic_search_scheme}
      ports:
        - 8081:8081


  amcart-frontend:
      image: amcart-frontend:latest
      container_name: amcart-frontend
      ports:
        - 80:80



volumes:
  elasticsearch-data:
    driver: local