---
apiVersion: v1
kind: Namespace
metadata:
  name: nagp-amcart-namespace


---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-service
  namespace: nagp-amcart-namespace
spec:
  selector:
    app: elasticsearch-service
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: nagp-amcart-namespace
data:
  xpack.security.enabled: 'false'
  discovery.type: single-node

---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: nagp-amcart-namespace
type: Opaque
data:
  ELASTIC_PASSWORD: cmFrZXNoQDEyMw==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: nagp-amcart-namespace
spec:
  selector:
      matchLabels:
        app: elasticsearch-service
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch-service
    spec:
      containers:
       - name: elasticsearch-service
         env:
          # - name: ES_JAVA_OPTS
          #   value: -Xms512m -Xmx512m
         image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
         ports:
         - containerPort: 9200
         envFrom:
            - configMapRef:
                name: elasticsearch-config
            - secretRef:
                name: elasticsearch-secret